### ISSUE TITLE
The getter 'validators' was called on null.

### ISSUE THREAD

**Issue by allanwolski** [edsonbonfim/form#3]
I'm getting an error after upgrading to version 0.0.5

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Input(state: _InputState#70296):
The getter 'validators' was called on null.
Receiver: null
Tried calling: validators

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _InputBaseState.didUpdateWidget (package:form/src/form.dart:533:41)
#2      StatefulElement.update (package:flutter/src/widgets/framework.dart:4690:58)
#3      Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
...
```

**Comment by edsonbonfim** [comment]
Could you show me an example of use where this error occurs?

**Comment by allanwolski** [comment]
The problem occurs when focusing on an error field.
If I remove setState the error does not occur.

```
_focusNode.addListener(() {
   setState(() {});
});
```

**Comment by allanwolski** [comment]
@edsonbonfim 

Any updates on this?

**Comment by guilhermedaldim** [comment]
Same issue here

**Comment by allanwolski** [comment]
@edsonbonfim

Has the plugin been discontinued?

**Comment by guilhermedaldim** [comment]
@edsonbonfim 

Any updates on this?
